abengkel/models/Ttuchd.php
<?php

namespace abengkel\models;

/**
 * This is the model class for table "ttuchd".
 *
 * @property string $UCNo
 * @property string $UCTgl
 * @property string $KodeTrans
 * @property string $PosKode
 * @property string $UCHrgLama
 * @property string $UCHrgBaru
 * @property string $UCSelisih
 * @property string $UCKeterangan
 * @property string $NoGL
 * @property string $Cetak
 * @property string $UserID
 */
class Ttuchd extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ttuchd';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['UCNo'], 'required'],
            [['UCTgl'], 'safe'],
            [['UCHrgLama', 'UCHrgBaru', 'UCSelisih'], 'number'],
            [['UCNo', 'NoGL'], 'string', 'max' => 10],
            [['KodeTrans'], 'string', 'max' => 4],
            [['PosKode'], 'string', 'max' => 20],
            [['UCKeterangan'], 'string', 'max' => 150],
            [['Cetak'], 'string', 'max' => 5],
            [['UserID'], 'string', 'max' => 15],
            [['UCNo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'UCNo'         => 'Uc No',
            'UCTgl'        => 'Uc Tgl',
            'KodeTrans'    => 'Kode Trans',
            'PosKode'      => 'Pos Kode',
            'UCHrgLama'    => 'Uc Hrg Lama',
            'UCHrgBaru'    => 'Uc Hrg Baru',
            'UCSelisih'    => 'Uc Selisih',
            'UCKeterangan' => 'Uc Keterangan',
            'NoGL'         => 'No Gl',
            'Cetak'        => 'Cetak',
            'UserID'       => 'User ID',
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function colGrid()
    {
        return [
            'UCNo'          => ['width' => 90,'label' => 'No UC','name'  => 'UCNo'],
            'UCTgl'         => ['width' => 120,'label' => 'Tanggal UC','name'  => 'UCTgl', 'formatter' => 'date', 'formatoptions' => ['srcformat' => "ISO8601Long",'newformat' => 'd/m/Y H:i:s']],
            'KodeTrans'     => ['width' => 60,'label' => 'TC','name'  => 'KodeTrans'],
            'PosKode'       => ['width' => 100,'label' => 'Pos Kode','name'  => 'PosKode'],
            'UCHrgLama'     => ['width' => 105,'label' => 'Hrg Lama','name'  => 'UCHrgLama', 'formatter' => 'number', 'align' => 'right'],
            'UCHrgBaru'     => ['width' => 105,'label' => 'Hrg Baru','name'  => 'UCHrgBaru', 'formatter' => 'number', 'align' => 'right'],
            'UCSelisih'     => ['width' => 105,'label' => 'Selisih','name'  => 'UCSelisih', 'formatter' => 'number', 'align' => 'right'],
            'NoGL'          => ['width' => 80,'label' => 'NoGL','name'  => 'NoGL'],
            'Cetak'         => ['width' => 70,'label' => 'Cetak','name'  => 'Cetak'],
            'UserID'        => ['width' => 105,'label' => 'UserID','name'  => 'UserID'],
			'UCKeterangan'  => ['width' => 300, 'label' => 'Keterangan', 'name' => 'UCKeterangan' ],		
        ];
    }

    /**
     * {@inheritdoc}
     * @return TtuchdQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TtuchdQuery(get_called_class());
    }
}

abengkel/controllers/TtuchdController.php
<?php
namespace abengkel\controllers;
use abengkel\components\AbengkelController;
use abengkel\components\Menu;
use abengkel\components\TdAction;
use abengkel\models\Tdkaryawan;
use abengkel\models\Tdlokasi;
use abengkel\models\Ttuchd;
use common\components\General;
use GuzzleHttp\Client;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
/**
 * TtuchdController implements the CRUD actions for Ttuchd model.
 */
class TtuchdController extends AbengkelController {
	public function actions() {
		return [
			'td' => [
				'class' => TdAction::class,
				'model' => Ttuchd::class,
			],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::class,
				'actions' => [
					'delete' => [ 'POST' ],
				],
			],
		];
	}
	/**
	 * Lists all Ttuchd models.
	 * @return mixed
	 */
	public function actionIndex() {
		if ( isset( $_GET[ 'action' ] ) && $_GET[ 'action' ] == 'display' ) {
			$post[ 'Action' ] = 'Display';
			$result           = Ttuchd::find()->callSP( $post );
			Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		}
		return $this->render( 'index', [
			'mode'    => '',
			'url_add' => Url::toRoute( [ 'ttuchd/td' ] )
		] );
	}
	/**
	 * Finds the Ttuchd model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param string $id
	 *
	 * @return Ttuchd the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = Ttuchd::findOne( $id ) ) !== null ) {
			return $model;
		}
		throw new NotFoundHttpException( 'The requested page does not exist.' );
	}
	/**
	 * Creates a new Ttuchd model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		$model               = new Ttuchd();
		$model->UCNo         = General::createTemporaryNo( 'UC', 'Ttuchd', 'UCNo' );
		$model->UCTgl        = date( 'Y-m-d H:i:s' );
		$model->KodeTrans    = 'UC';
		$model->PosKode      = $this->LokasiKode();
		$model->UCHrgLama    = 0;
		$model->UCHrgLama    = 0;
		$model->UCSelisih    = 0;
		$model->UCKeterangan = "--";
		$model->UserID       = $this->UserID();
		$model->NoGL         = "--";
		$model->Cetak        = "Belum";
		$model->save();
		$post             = $model->attributes;
		$post[ 'Action' ] = 'Insert';
		$result           = Ttuchd::find()->callSP( $post );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		$dsSetup               = Ttuchd::find()->ttuchdFillByNo()->where( [ 'ttuchd.UCNo' => $model->UCNo ] )
		                               ->asArray( true )->one();
		$id                    = $this->generateIdBase64FromModel( $model );
		$dsSetup[ 'UCNoView' ] = $result[ 'UCNo' ];
		return $this->render( 'create', [
			'model'   => $model,
			'dsSetup' => $dsSetup,
			'id'      => $id,
		] );
	}
	/**
	 * Updates an existing Ttuchd model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate( $id ) {
		$index = \yii\helpers\Url::toRoute( [ 'ttuchd/index' ] );
		if ( ! isset( $_GET[ 'action' ] ) ) {
			return $this->redirect( $index );
		}
		/** @var Ttuchd $model */
		$model   = $this->findModelBase64( 'Ttuchd', $id );
		$dsSetup = Ttuchd::find()->ttuchdFillByNo()->where( [ 'ttuchd.UCNo' => $model->UCNo ] )
		                 ->asArray( true )->one();
		if ( Yii::$app->request->isPost ) {
			$post             = array_merge( $dsSetup, \Yii::$app->request->post() );
			$_POST[ 'UCTgl' ] = $_POST[ 'UCTgl' ] . ' ' . $_POST[ 'UCJam' ];
			$post[ 'Action' ] = 'Update';
			$result           = Ttuchd::find()->callSP( $post );
			Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
			$model              = Ttuchd::findOne( $result[ 'UCNo' ] );
			$id                 = $this->generateIdBase64FromModel( $model );
			$post[ 'UCNoView' ] = $result[ 'UCNo' ];
			if ( $result[ 'status' ] == 0 && $result[ 'status' ] !== null ) {
				return $this->redirect( [ 'ttuchd/update', 'action' => 'display', 'id' => $id ] );
			} else {
				return $this->render( 'update', [
					'model'   => $model,
					'dsSetup' => $post,
					'id'      => $id,
				] );
			}
		}
		$dsSetup[ 'Action' ] = 'Load';
		$result              = Ttuchd::find()->callSP( $dsSetup );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		$dsSetup[ 'UCNoView' ] = $result[ 'UCNo' ];
		$dsSetup[ 'UCNoView' ] = $_GET[ 'UCNoView' ] ?? $result[ 'UCNo' ];
		return $this->render( 'update', [
			'model'   => $model,
			'dsSetup' => $dsSetup,
			'id'      => $id
		] );
	}
	/**
	 * Deletes an existing Ttuchd model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete( $id ) {
		/** @var Ttuchd $model */
		$model             = $this->findModelBase64( 'Ttuchd', $_POST[ 'id' ] );
		$_POST[ 'UCNo' ]   = $model->UCNo;
		$_POST[ 'Action' ] = 'Delete';
		$result            = Ttuchd::find()->callSP( $_POST );
		if ( $result[ 'status' ] == 0 ) {
			return $this->responseSuccess( $result[ 'keterangan' ] );
		} else {
			return $this->responseFailed( $result[ 'keterangan' ] );
		}
	}
	public function actionCancel( $id, $action ) {
		/** @var Ttuchd $model */
		$model             = $this->findModelBase64( 'Ttuchd', $id );
		$_POST[ 'UCNo' ]   = $model->UCNo;
		$_POST[ 'UCTgl' ]  = $_POST[ 'UCTgl' ] . ' ' . $_POST[ 'UCJam' ];
		$_POST[ 'Action' ] = 'Cancel';
		$result            = Ttuchd::find()->callSP( $_POST );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		if ( $result[ 'UCNo' ] == '--' ) {
			return $this->redirect( [ 'index' ] );
		} else {
			$model = Ttuchd::findOne( $result[ 'UCNo' ] );
			return $this->redirect( [ 'ttuchd/update', 'action' => 'display', 'id' => $this->generateIdBase64FromModel( $model ) ] );
		}
	}
	public function actionPrint( $id ) {
		unset( $_POST[ '_csrf-app' ] );
		$_POST             = array_merge( $_POST, Yii::$app->session->get( '_company' ) );
		$_POST[ 'db' ]     = base64_decode( $_COOKIE[ '_outlet' ] );
		$_POST[ 'UserID' ] = Menu::getUserLokasi()[ 'UserID' ];
		$client            = new Client( [
			'headers' => [ 'Content-Type' => 'application/octet-stream' ]
		] );
		$response          = $client->post( Yii::$app->params['H2'][$_POST['db']]['host_report'] . '/abengkel/fuchd', [
			'body' => Json::encode( $_POST )
		] );
//		return $response->getBody();
        $html                 = $response->getBody();
        return str_replace( "<BODY", '<BODY onload="window.print()"', $html );
	}
}

abengkel/views/ttuchd/create.php
<?php
use common\components\Custom;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Ttuchd */
$params                          = '&id=' . $id . '&action=create';
$cancel = Custom::url(\Yii::$app->controller->id.'/cancel'.$params );
$this->title                     = 'Tambah - Standard Cost';
?>
<div class="ttuchd-create">
    <?= $this->render('_form', [
        'model'     => $model,
        'id'        =>$id,
        'dsSetup'   => $dsSetup,
        'url'       => [
            'update' => Custom::url( \Yii::$app->controller->id . '/update' . $params ),
            'print'  => Custom::url( \Yii::$app->controller->id . '/print' . $params ),
            'cancel' => $cancel,
            'detail' => Url::toRoute( [ 'ttucit/index','action' => 'create' ] ),
        ]
    ]) ?>

</div>

abengkel/views/ttuchd/index.php
<?php
use abengkel\assets\AppAsset;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Update Standar Cost';
$this->params['breadcrumbs'][] = $this->title;
$arr                           = [
	'cmbTxt'    => [
		'UCNo'      => 'Uc No',
		'KodeTrans' => 'Kode Trans',
		'PosKode'   => 'Pos Kode',
		'NoGL'      => 'No Gl',
		'Cetak'     => 'Cetak',
		'UserID'    => 'User ID',
	],
	'cmbTgl'    => [
		'UCTgl'     => 'Uc Tgl',
	],
	'cmbNum'    => [
		'UCHrgLama' => 'Uc Hrg Lama',
		'UCHrgBaru' => 'Uc Hrg Baru',
		'UCSelisih' => 'Uc Selisih',
	],
	'sortname'  => "UCTgl",
	'sortorder' => 'desc'
];
$this->registerJsVar( 'setcmb', $arr );
AppAsset::register( $this );
?>
    <div class="panel panel-default">
        <div class="panel-body">
			<?= $this->render( '../_search' ); ?>
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
<?php
$this->registerJs( \abengkel\components\TdUi::mainGridJs( \abengkel\models\Ttuchd::className(), 'Update Standar Cost',
    [
        'url_delete' => Url::toRoute( [ 'ttuchd/delete' ] ),
    ]), \yii\web\View::POS_READY );

abengkel/views/ttuchd/update.php
<?php
use common\components\Custom;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Ttuchd */
$params                          = '&id=' . $id . '&action=update';
$cancel = Custom::url(\Yii::$app->controller->id.'/cancel'.$params );
$this->title                     = 'Edit - Standard Cost: ' . $dsSetup['UCNoView'];
?>
<div class="ttuchd-update">
    <?= $this->render('_form', [
        'model' => $model,
        'dsSetup' => $dsSetup,
        'id'=>$id,
        'url'    => [
            'update' => Custom::url( \Yii::$app->controller->id . '/update' . $params ),
            'print'  => Custom::url( \Yii::$app->controller->id . '/print' . $params ),
            'cancel' => $cancel,
            'detail' => Url::toRoute( [ 'ttucit/index','action' => 'update' ] ),
                /*
                'print'        => Url::toRoute( [ \Yii::$app->controller->id . '/print', 'id' => $id, 'action' => 'print' ] ),
                */
        ]
    ]) ?>

</div>