afinance/models/Tdsale.php
<?php
namespace afinance\models;
/**
 * This is the model class for table "tdsales".
 *
 * @property string $SalesKode
 * @property string $SalesNama
 * @property string $SalesAlamat
 * @property string $SalesTelepon
 * @property string $SalesStatus
 * @property string $SalesKeterangan
 * @property string $SalesKodeAstra
 * @property string $TeamKode
 * @property string $SalesHSOid
 * @property string $SalesPass
 */
class Tdsale extends \yii\db\ActiveRecord {
	/**
	 * {@inheritdoc}
	 */
	public static function tableName() {
		return 'tdsales';
	}
	/**
	 * {@inheritdoc}
	 */
	public function rules() {
		return [
			[ [ 'SalesKode' ], 'required' ],
			[ [ 'SalesKode' ], 'string', 'max' => 10 ],
			[ [ 'SalesNama' ], 'string', 'max' => 50 ],
			[ [ 'SalesAlamat', 'SalesTelepon' ], 'string', 'max' => 75 ],
			[ [ 'SalesStatus', 'SalesPass' ], 'string', 'max' => 1 ],
			[ [ 'SalesKeterangan' ], 'string', 'max' => 100 ],
			[ [ 'SalesKodeAstra' ], 'string', 'max' => 25 ],
			[ [ 'TeamKode', 'SalesHSOid' ], 'string', 'max' => 15 ],
			[ [ 'SalesKode' ], 'unique' ],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels() {
		return [
			'SalesKode'       => 'Kode',
			'SalesNama'       => 'Nama',
			'SalesAlamat'     => 'Alamat',
			'SalesTelepon'    => 'Telepon',
			'SalesStatus'     => 'Status',
			'SalesKeterangan' => 'Keterangan',
			'SalesKodeAstra'  => 'Kode Astra',
			'TeamKode'        => 'Team Kode',
			'SalesHSOid'      => 'HSO ID',
			'SalesPass'       => 'Sales Pass',
		];
	}
	public static function colGrid() {
		return [
			'SalesKode'       => 'Kode',
			'SalesNama'       => 'Nama',
			'SalesAlamat'     => 'Alamat',
			'SalesTelepon'    => 'Telepon',
			'SalesStatus'     => 'Status',
			'SalesKeterangan' => 'Keterangan'
		];
	}
	/**
	 * {@inheritdoc}
	 * @return TdsaleQuery the active query used by this AR class.
	 */
	public static function find() {
		return new TdsaleQuery( get_called_class() );
	}
}

afinance/controllers/TdsaleController.php
<?php
namespace afinance\controllers;
use afinance\components\AfinanceController;
use afinance\components\TdAction;
use afinance\models\Tdsale;
use afinance\models\TdsaleSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
/**
 * TdsaleController implements the CRUD actions for Tdsale model.
 */
class TdsaleController extends AfinanceController {
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'delete' => [ 'POST' ],
				],
			],
		];
	}
	public function actions() {
		return [
			'td' => [
				'class' => TdAction::className(),
				'model' => Tdsale::className(),
			],
		];
	}
	/**
	 * Lists all Tdsale models.
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new TdsaleSearch();
		$dataProvider = $searchModel->search( Yii::$app->request->queryParams );
		return $this->render( 'index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		] );
	}
	/**
	 * Displays a single Tdsale model.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView( $id ) {
		return $this->render( 'view', [
			'model' => $this->findModel( $id ),
		] );
	}
	/**
	 * Creates a new Tdsale model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new Tdsale();
		if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
			return $this->redirect( [ 'view', 'id' => $model->SalesKode ] );
		}
		return $this->render( 'create', [
			'model' => $model,
		] );
	}
	/**
	 * Updates an existing Tdsale model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate( $id ) {
		$model = $this->findModelBase64( 'Tdsale', $id );
		if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
			return $this->redirect( [ 'view', 'id' => $model->SalesKode ] );
		}
		return $this->render( 'update', [
			'model' => $model,
		] );
	}
	/**
	 * Deletes an existing Tdsale model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete( $id ) {
		$this->findModel( $id )->delete();
		return $this->redirect( [ 'index' ] );
	}
	/**
	 * Finds the Tdsale model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param string $id
	 *
	 * @return Tdsale the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = Tdsale::findOne( $id ) ) !== null ) {
			return $model;
		}
		throw new NotFoundHttpException( 'The requested page does not exist.' );
	}
}

afinance/controllers/TdsalesController.php
<?php
namespace afinance\controllers;
use afinance\components\AfinanceController;
use afinance\components\TdAction;
use afinance\models\Tdsales;

use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
/**
 * TdsaleController implements the CRUD actions for Tdsale model.
 */
class TdsalesController extends AfinanceController {
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'delete' => [ 'POST' ],
				],
			],
		];
	}
	public function actions() {
		return [
			'td' => [
				'class' => TdAction::className(),
				'model' => Tdsales::className(),
			],
		];
	}
	/**
	 * Lists all Tdsale models.
	 * @return mixed
	 */
	public function actionIndex() {
		return $this->render( 'index');
	}
	/**
	 * Displays a single Tdsale model.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView( $id ) {
		return $this->render( 'view', [
			'model' => $this->findModel( $id ),
		] );
	}
	/**
	 * Finds the Tdsale model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param string $id
	 *
	 * @return Tdsales the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = Tdsales::findOne( $id ) ) !== null ) {
			return $model;
		}
		throw new NotFoundHttpException( 'The requested page does not exist.' );
	}
	/**
	 * Creates a new Tdsale model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new Tdsales();
		if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
			return $this->redirect( [ 'index', 'id' => $this->generateIdBase64FromModel( $model ) ] );
		}
		return $this->render( 'create', [
			'model' => $model,
		] );
	}
	/**
	 * Updates an existing Tdsale model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate( $id ) {
		$model = $this->findModelBase64( 'Tdsale', $id );
		if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
			return $this->redirect( [ 'index', 'id' => $this->generateIdBase64FromModel( $model ) ] );
		}
		return $this->render( 'update', [
			'model' => $model,
			'id'    => $this->generateIdBase64FromModel( $model ),
		] );
	}
	/**
	 *
	 */
	public function actionFind() {
		$params = \Yii::$app->request->post();
		$rows   = [];
		if ( $params[ 'mode' ] === 'combo' ) {
			$value     = isset( $params[ 'value' ] ) ? $params[ 'value' ] : 'SalesKode';
			$label     = isset( $params[ 'label' ] ) ? $params[ 'label' ] : [ 'SalesNama' ];
			$order     = isset( $params[ 'order' ] ) ? $params[ 'order' ] : [];
			$condition = isset( $params[ 'condition' ] ) ? $params[ 'condition' ] : [];
			$params_cmb    = isset( $params[ 'params' ] ) ? $params[ 'params' ] : [];
			$allOption = isset( $params[ 'allOption' ] ) ? $params[ 'allOption' ] : false;
			$rows      = Tdsales::find()->select2( $value, $label, $order, [ 'condition' => $condition, 'params' => $params_cmb ], $allOption );
		}
		return $this->responseDataJson( $rows );
	}
	/**
	 * Deletes an existing Tdsale model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
	public function actionDelete( $id ) {
		$this->findModel( $id )->delete();
		return $this->redirect( [ 'index' ] );
	}
}

afinance/views/tdsale/_form.php
<?php
use afinance\models\Tdteam;
use kartik\number\NumberControl;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model afinance\models\Tdsale */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="col-md-12 col-xl-12 col-lg-12">
    <div class="box box-primary ">
		<?php $form = ActiveForm::begin( [
			'class' => 'form-horizontal'
		] ); ?>
        <div class="box-body ">
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesKode' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesKode' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesKodeAstra' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesKodeAstra' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesHSOid' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesHSOid' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesNama' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesNama' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'TeamKode' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'TeamKode' )->widget( Select2::classname(), [
						'value'         => $model->TeamKode,
						'options'       => [ 'placeholder' => 'Filter as you type ...' ],
						'pluginOptions' => [ 'highlight' => true ],
						'data'          => Tdteam::find()->select2()
					] )->label( false ) ?>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesAlamat' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesAlamat' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesTelepon' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesTelepon' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesKeterangan' ) ?>:</label>
                <div class="col-sm-18">
					<?= $form->field( $model, 'SalesKeterangan' )->textInput( [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-6"><?= $model->getAttributeLabel( 'SalesStatus' ) ?>:</label>
                <div class="col-sm-18">
			        <?= $form->field( $model, 'SalesStatus' )->dropDownList( [
				        'A' => 'AKTIF',
				        'N' => 'NON AKTIF',
			        ], [ 'maxlength' => true ] )->label( false ) ?>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="pull-right">-
				<?= Html::submitButton( 'Simpan', [ 'class' => 'btn btn-success' ] ) ?>
                <a href="<?= Url::to( [ 'tdsales/index' ] ) ?>" class="btn btn-warning" role="button">Batal</a>
            </div>
        </div>
		<?php ActiveForm::end(); ?>
    </div>
</div>

afinance/views/tdsale/create.php
<?php
/* @var $this yii\web\View */
/* @var $model afinance\models\Tdsale */
$this->title                   = 'Create Sales';
$this->params['breadcrumbs'][] = [ 'label' => 'Sales', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tdsale-create">
	<?= $this->render( '_form', [
		'model' => $model,
	] ) ?>
</div>

afinance/views/tdsale/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel afinance\models\TdsaleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
use afinance\assets\AppAsset;
AppAsset::register($this);
$this->title = 'Sales';
$this->params['breadcrumbs'][] = $this->title;
$arr                           = [
	'cmbTxt' => [
		'SalesKode' => 'Kode',
		'SalesNama' => 'Nama',
		'SalesAlamat' => 'Alamat',
		'SalesTelepon' => 'Telepon',
		'SalesStatus' => 'Status',
		'SalesKeterangan' => 'Keterangan',
		'SalesKodeAstra' => 'Kode Astra',
		'TeamKode' => 'Team Kode',
		'SalesHSOid' => 'HSO ID',
	],
	'cmbTgl' => [
	],
	'cmbNum' => [
	],
	'sortname'  => "SalesStatus asc,SalesKode asc,SalesNama",
	'sortorder' => 'asc'
];
$this->registerJsVar( 'setcmb', $arr );
?>
    <div class="panel panel-default">
        <div class="panel-body">
			<?= $this->render( '../_search' ); ?>
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
<?php
$this->registerJs( \afinance\components\TdUi::mainGridJs( \afinance\models\Tdsale::className(),'Sales' ), \yii\web\View::POS_READY );

afinance/views/tdsale/update.php
<?php
/* @var $this yii\web\View */
/* @var $model afinance\models\Tdsale */
$this->title                   = 'Update Sales: ' . $model->SalesKode;
$this->params['breadcrumbs'][] = [ 'label' => 'Sales', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = [ 'label' => $model->SalesKode, 'url' => [ 'view', 'id' => $model->SalesKode ] ];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tdsale-update">
	<?= $this->render( '_form', [
		'model' => $model,
	] ) ?>
</div>