abengkel/models/Ttujhd.php
<?php

namespace abengkel\models;

/**
 * This is the model class for table "ttujhd".
 *
 * @property string $UJNo
 * @property string $UJTgl
 * @property string $UJKeterangan
 * @property string $KodeTrans
 * @property string $PosKode
 * @property string $Cetak
 * @property string $UserID
 */
class Ttujhd extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ttujhd';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['UJNo'], 'required'],
            [['UJTgl'], 'safe'],
            [['UJNo'], 'string', 'max' => 10],
            [['UJKeterangan'], 'string', 'max' => 150],
            [['KodeTrans'], 'string', 'max' => 4],
            [['PosKode'], 'string', 'max' => 20],
            [['Cetak', 'UserID'], 'string', 'max' => 15],
            [['UJNo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'UJNo' => 'Uj No',
            'UJTgl' => 'Uj Tgl',
            'UJKeterangan' => 'Uj Keterangan',
            'KodeTrans' => 'Kode Trans',
            'PosKode' => 'Pos Kode',
            'Cetak' => 'Cetak',
            'UserID' => 'User ID',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function colGrid()
    {
        return [
            'UJNo'         => ['width' => 90,'label' => 'No UJ','name'  => 'UJNo'],
            'UJTgl'        => ['width' => 120,'label' => 'Tgl UJ','name'  => 'UJTgl', 'formatter' => 'date', 'formatoptions' => ['srcformat' => "ISO8601Long",'newformat' => 'd/m/Y H:i:s']],
            'KodeTrans'    => ['width' => 50,'label' => 'TC','name'  => 'KodeTrans'],
            'PosKode'      => ['width' => 90,'label' => 'PosKode','name'  => 'PosKode'],
            'Cetak'        => ['width' => 60,'label' => 'Cetak','name'  => 'Cetak'],
            'UJKeterangan' => ['width' => 240,'label' => 'Keterangan','name'  => 'UJKeterangan'],
            'UserID'       => ['width' => 90,'label' => 'UserID','name'  => 'UserID'],
        ];
    }

    /**
     * {@inheritdoc}
     * @return TtujhdQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TtujhdQuery(get_called_class());
    }
}

abengkel/controllers/TtujhdController.php
<?php
namespace abengkel\controllers;
use abengkel\components\AbengkelController;
use abengkel\components\Menu;
use abengkel\components\TdAction;
use abengkel\models\Tdlokasi;
use abengkel\models\Tdsupplier;
use abengkel\models\Ttpohd;
use abengkel\models\Ttujhd;
use common\components\General;
use GuzzleHttp\Client;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
/**
 * TtujhdController implements the CRUD actions for Ttujhd model.
 */
class TtujhdController extends AbengkelController {
	public function actions() {
		return [
			'td' => [
				'class' => TdAction::class,
				'model' => Ttujhd::class,
			],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class'   => VerbFilter::class,
				'actions' => [
					'delete' => [ 'POST' ],
				],
			],
		];
	}
	/**
	 * Lists all Ttujhd models.
	 * @return mixed
	 */
	public function actionIndex() {
		if ( isset( $_GET[ 'action' ] ) && $_GET[ 'action' ] == 'display' ) {
			$post[ 'Action' ] = 'Display';
			$result           = Ttujhd::find()->callSP( $post );
			Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		}
		return $this->render( 'index', [
			'mode'    => '',
			'url_add' => Url::toRoute( [ 'ttujhd/td' ] )
		] );
		/*
		return $this->render( 'index' );
		*/
	}
	/**
	 * Displays a single Ttujhd model.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView( $id ) {
		return $this->render( 'index', [
			'model' => $this->findModel( $id ),
		] );
	}
	/**
	 * Finds the Ttujhd model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param string $id
	 *
	 * @return Ttujhd the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = Ttujhd::findOne( $id ) ) !== null ) {
			return $model;
		}
		throw new NotFoundHttpException( 'The requested page does not exist.' );
	}
	/**
	 * Creates a new Ttujhd model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		$model               = new Ttujhd();
		$model->UJNo         = General::createTemporaryNo( 'UJ', 'Ttujhd', 'UJNo' );
		$model->UJTgl        = date( 'Y-m-d H:i:s' );
		$model->UJKeterangan = "--";
		$model->KodeTrans    = "UJ";
		$model->PosKode      = $this->LokasiKode();
		$model->Cetak        = "Belum";
		$model->UserID       = $this->UserID();
		$model->save();
		$post             = $model->attributes;
		$post[ 'Action' ] = 'Insert';
		$result           = Ttujhd::find()->callSP( $post );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		$dsSetup               = Ttujhd::find()->ttujhdFillByNo()
		                               ->where( [ 'ttujhd.UJNo' => $model->UJNo ] )->asArray( true )->one();
		$dsSetup[ 'UJJam' ]    = $dsSetup[ 'UJTgl' ];
		$dsSetup[ 'NoGL' ]     = '--';
		$dsSetup[ 'UJTgl' ]    = date( 'Y-m-d H:i:s' );
		$dsSetup[ 'UJTgl' ]    = date( 'Y-m-d H:i:s' );
		$id                    = $this->generateIdBase64FromModel( $model );
		$dsSetup[ 'UJNoView' ] = $result[ 'UJNo' ];
		return $this->render( 'create', [
			'model'   => $model,
			'dsSetup' => $dsSetup,
			'id'      => $id
		] );
	}
	/**
	 * Updates an existing Ttujhd model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate( $id ) {
		$index = \yii\helpers\Url::toRoute( [ 'ttujhd/index' ] );
		if ( ! isset( $_GET[ 'action' ] ) ) {
			return $this->redirect( $index );
		}
		$model   = $this->findModelBase64( 'Ttujhd', $id );
		$dsSetup = Ttujhd::find()->ttujhdFillByNo()->where( [ 'ttujhd.UJNo' => $model->UJNo ] )
		                 ->asArray( true )->one();
		if ( Yii::$app->request->isPost ) {
			$post             = array_merge( $dsSetup, \Yii::$app->request->post() );
			$_POST[ 'UJTgl' ] = $_POST[ 'UJTgl' ] . ' ' . $_POST[ 'UJJam' ];
			$post[ 'Action' ] = 'Update';
			$result           = Ttujhd::find()->callSP( $post );
			Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
			$model              = Ttujhd::findOne( $result[ 'UJNo' ] );
			$id                 = $this->generateIdBase64FromModel( $model );
			$post[ 'UJNoView' ] = $result[ 'UJNo' ];
			if ( $result[ 'status' ] == 0 && $result[ 'status' ] !== null ) {
				return $this->redirect( [ 'ttujhd/update', 'action' => 'display', 'id' => $id ] );
			} else {
				return $this->render( 'update', [
					'model'   => $model,
					'dsSetup' => $post,
					'id'      => $id,
				] );
			}
		}
		$dsSetup[ 'UJJam' ]  = $dsSetup[ 'UJTgl' ];
		$dsSetup[ 'NoGL' ]   = '--';
		$dsSetup[ 'UJTgl' ]  = General::asDate( $dsSetup[ 'UJTgl' ] );
		$dsSetup[ 'Action' ] = 'Load';
		$result              = Ttujhd::find()->callSP( $dsSetup );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		$dsSetup[ 'UJNoView' ] = $_GET[ 'UJNoView' ] ?? $result[ 'UJNo' ];
		return $this->render( 'update', [
			'model'   => $model,
			'dsSetup' => $dsSetup,
			'id'      => $id
		] );
	}
	/**
	 * Deletes an existing Ttujhd model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete( $id ) {
		/** @var Ttujhd $model */
		$model             = $this->findModelBase64( 'Ttujhd', $_POST[ 'id' ] );
		$_POST[ 'UJNo' ]   = $model->UJNo;
		$_POST[ 'Action' ] = 'Delete';
		$result            = Ttujhd::find()->callSP( $_POST );
		if ( $result[ 'status' ] == 0 ) {
			return $this->responseSuccess( $result[ 'keterangan' ] );
		} else {
			return $this->responseFailed( $result[ 'keterangan' ] );
		}
	}
	public function actionCancel( $id ) {
		/** @var Ttujhd $model */
		$model             = $this->findModelBase64( 'Ttujhd', $id );
		$_POST[ 'UJNo' ]   = $model->UJNo;
		$_POST[ 'UJTgl' ]  = $_POST[ 'UJTgl' ] . ' ' . $_POST[ 'UJJam' ];
		$_POST[ 'Action' ] = 'Cancel';
		$result            = Ttujhd::find()->callSP( $_POST );
		Yii::$app->session->addFlash( ( $result[ 'status' ] == 0 ) ? 'success' : 'warning', $result[ 'keterangan' ] );
		if ( $result[ 'UJNo' ] == '--' ) {
			return $this->redirect( [ 'index' ] );
		} else {
			$model = Ttujhd::findOne( $result[ 'UJNo' ] );
			return $this->redirect( [ 'ttujhd/update', 'action' => 'display', 'id' => $this->generateIdBase64FromModel( $model ) ] );
		}
	}
	public function actionPrint( $id ) {
		unset( $_POST[ '_csrf-app' ] );
		$_POST             = array_merge( $_POST, Yii::$app->session->get( '_company' ) );
		$_POST[ 'db' ]     = base64_decode( $_COOKIE[ '_outlet' ] );
		$_POST[ 'UserID' ] = Menu::getUserLokasi()[ 'UserID' ];
		$client            = new Client( [
			'headers' => [ 'Content-Type' => 'application/octet-stream' ]
		] );
		$response          = $client->post( Yii::$app->params['H2'][$_POST['db']]['host_report'] . '/abengkel/fujhd', [
			'body' => Json::encode( $_POST )
		] );
//		return $response->getBody();
        $html                 = $response->getBody();
        return str_replace( "<BODY", '<BODY onload="window.print()"', $html );
	}
}

abengkel/views/ttujhd/_form.php
<?php
use abengkel\components\FormField;
use common\components\Custom;
use common\components\General;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\web\View;
use yii\widgets\ActiveForm;
\abengkel\assets\AppAsset::register( $this );
/* @var $this yii\web\View */
/* @var $model abengkel\models\Ttujhd */
/* @var $form yii\widgets\ActiveForm */

$format          = <<< SCRIPT
function matchCustom(params, data) {
    if ($.trim(params.term) === '') {
      return data;
    }
    if (typeof data.text === 'undefined') {
      return null;
    }
    if (data.text.toLowerCase().indexOf(params.term.toLowerCase()) > -1 || data.id.toLowerCase().indexOf(params.term.toLowerCase()) > -1) {
      var modifiedData = $.extend({}, data, true);
      return modifiedData;
    }
    return null;
}
SCRIPT;
$escape          = new JsExpression( "function(m) { return m; }" );
$this->registerJs( $format, View::POS_HEAD );
?>
    <div class="ttujhd-form">
		<?php
        $form = ActiveForm::begin( [ 'id' => 'form_ttujhd_id','action' => $url[ 'update' ] ] );
		\abengkel\components\TUi::form(
			[
				'class' => "row-no-gutters",
				'items' => [
					[ 'class' => "form-group col-md-24",
					  'items' => [
						  [ 'class' => "col-sm-2", 'items' => ":LabelNumber" ],
						  [ 'class' => "col-sm-3", 'items' => ":Number" ],
						  [ 'class' => "col-sm-1"],
						  [ 'class' => "col-sm-1",'items' => ":LabelTgl" ],
						  [ 'class' => "col-sm-2", 'items' => ":Tgl" ],
						  [ 'class' => "col-sm-2", 'items' => ":Jam" ],
						  [ 'class' => "col-sm-7" ],
						  [ 'class' => "col-sm-1", 'items' => ":LabelTC" ],
						  [ 'class' => "col-sm-5", 'items' => ":TC" ],
					  ],
					],
					[
						'class' => "row col-md-24",
						'style' => "margin-bottom: 6px;",
						'items' => '<table id="detailGrid"></table><div id="detailGridPager"></div>'
					],
					[ 'class' => "form-group col-md-24", 'style' => "",
					  'items' => [
						  [ 'class' => "col-sm-2", 'items' => ":LabelUJKeterangan" ],
						  [ 'class' => "col-sm-13", 'items' => ":UJKeterangan" ],
						  [ 'class' => "col-sm-1"],
						  [ 'class' => "col-sm-2", 'items' => ":LabelStatus" ],
						  [ 'class' => "col-sm-2", 'items' => ":Status" ],
					  ],
					],
				]
			],
			[ 'class' => "pull-right", 'items' => ":btnPrint :btnAction" ],
			[
				/* label */
				":LabelNumber"       => '<label class="control-label" style="margin: 0; padding: 6px 0;">Nomor UJ</label>',
				":LabelTgl"          => '<label class="control-label" style="margin: 0; padding: 6px 0;">Tgl UJ</label>',
				":LabelTC"           => '<label class="control-label" style="margin: 0; padding: 6px 0;">TC</label>',
				":LabelUJKeterangan" => '<label class="control-label" style="margin: 0; padding: 6px 0;">Keterangan</label>',
				":LabelStatus"       => '<label class="control-label" style="margin: 0; padding: 6px 0;">Status Cetak</label>',
				/* component */
                ":Number"           => Html::textInput( 'UJNoView', $dsSetup[ 'UJNoView' ], [ 'class' => 'form-control','readonly' => 'readonly' ] ) .
                                        Html::textInput( 'UJNo', $dsSetup[ 'UJNo' ], [ 'class' => 'hidden' ] ) ,
                ":UJKeterangan"     => Html::textarea( 'UJKeterangan', $dsSetup[ 'UJKeterangan' ], [ 'class' => 'form-control', 'maxlength' => '150' ] ),
                ":Tgl"              => FormField::dateInput( [ 'name' => 'UJTgl', 'config' => [ 'value' => General::asDate( $dsSetup[ 'UJTgl' ] ) ] ] ),
                ":Jam"              => FormField::timeInput( [ 'name' => 'UJJam', 'config' => [ 'value' => $dsSetup[ 'UJTgl' ] ] ] ),
                ":TC"               => FormField::combo( 'KodeTrans', [  'name'=> "KodeTrans",'config' => ['value' => $dsSetup[ 'KodeTrans' ], 'data' => [
                                        'UJ' => 'UJ - Update Harga Jasa',] ], 'extraOptions'  => [ 'simpleCombo' => true ] ] ),
                ":Status"           => Html::textInput( 'Cetak', $dsSetup[ 'Cetak' ], [ 'class' => 'form-control','readonly' => 'readonly' ] ),
			],
            [
                'url_main' => 'ttujhd',
                'url_id' => $id,
            ]
		);
		ActiveForm::end();
		?>
    </div>
<?php
$urlDetail = $url[ 'detail' ];
$urlPrint  = $url[ 'print' ];
$readOnly  = ( $_GET['action'] == 'view' ? 'true' : 'false' );
$barang    = \common\components\General::cCmd(
        "SELECT JasaKode, JasaNama, JasaGroup, JasaHrgBeli, JasaHrgJual, JasaWaktuKerja, JasaWaktuSatuan, JasaWaktuKerjaMenit, JasaStatus, JasaKeterangan FROM tdjasa
WHERE JasaStatus = 'A' 
UNION
SELECT JasaKode, JasaNama, JasaGroup, JasaHrgBeli, JasaHrgJual, JasaWaktuKerja, JasaWaktuSatuan, JasaWaktuKerjaMenit, JasaStatus, JasaKeterangan FROM tdjasa
WHERE JasaKode IN 
(SELECT ttUJit.JasaKode FROM ttUJit INNER JOIN tdjasa ON ttUJit.JasaKode = tdjasa.JasaKode 
 WHERE ttUJit.UJNo = :UJNo AND tdjasa.JasaStatus = 'N' GROUP BY ttUJit.JasaKode )
ORDER BY JasaStatus, JasaKode",[':UJNo' => $dsSetup['UJNo'] ] )->queryAll();

$this->registerJsVar( '__Barang', json_encode( $barang ) );
$this->registerJs( <<< JS
     var __BrgKode = JSON.parse(__Barang);
     __BrgKode = $.map(__BrgKode, function (obj) {
                      obj.id = obj.JasaKode;
                      obj.text = obj.JasaKode;
                      return obj;
                    });
     var __BrgNama = JSON.parse(__Barang);
     __BrgNama = $.map(__BrgNama, function (obj) {
                      obj.id = obj.JasaNama;
                      obj.text = obj.JasaNama;
                      return obj;
                    });
    
        
     $('#detailGrid').utilJqGrid({        
        editurl: '$urlDetail',       
        height: 300,
        extraParams: {
            UJNo: $('input[name="UJNo"]').val()
        },
        rownumbers: true,  
        loadonce:true,
        rowNum: 1000,
        readOnly: $readOnly,         
        colModel: [
            { template: 'actions' },
            {
                name: 'JasaKode',
                label: 'Kode',
                width: 150,
                editable: true,
                editor: {
                    type: 'select2',
                    data: __BrgKode,
                    events:{
                        'select2:select': function (e) {
						    var data = e.params.data;
						    // console.log(data);
						    let rowid = $(this).attr('rowid');
						    $('[id="'+rowid+'_'+'BrgSatuan'+'"]').val(data.JasaWaktuSatuan);
                            $('[id="'+rowid+'_'+'UJHrgJualLama'+'"]').utilNumberControl().val(data.JasaHrgJual);
                            $('[id="'+rowid+'_'+'UJHrgJualBaru'+'"]').utilNumberControl().val(data.JasaHrgJual);
                            $('[id="'+rowid+'_'+'UJHrgBeliLama'+'"]').utilNumberControl().val(data.JasaHrgBeli);
                            $('[id="'+rowid+'_'+'UJHrgBeliBaru'+'"]').utilNumberControl().val(data.JasaHrgBeli);
                            $('[id="'+rowid+'_'+'JasaGroup'+'"]').val(data.JasaGroup);
                            $('[id="'+rowid+'_'+'JasaNama'+'"]').val(data.JasaNama); // Select the option with a value of '1'
                            $('[id="'+rowid+'_'+'JasaNama'+'"]').trigger('change');
                            window.hitungLine();
						}
                    }                 
                }
            },
            {
                name: 'JasaNama',
                label: 'Nama Jasa',
                width: 230,
                editable: true,
                editor: {
                    type: 'select2',
                    data: __BrgNama,
                    events:{
                        'select2:select': function (e) {
						    var data = e.params.data;
						    console.log(data);
						    let rowid = $(this).attr('rowid');
						    $('[id="'+rowid+'_'+'BrgSatuan'+'"]').val(data.JasaWaktuSatuan);
                            $('[id="'+rowid+'_'+'UJHrgJualLama'+'"]').utilNumberControl().val(data.JasaHrgJual);
                            $('[id="'+rowid+'_'+'UJHrgJualBaru'+'"]').utilNumberControl().val(data.JasaHrgJual);
                            $('[id="'+rowid+'_'+'UJHrgBeliLama'+'"]').utilNumberControl().val(data.JasaHrgBeli);
                            $('[id="'+rowid+'_'+'UJHrgBeliBaru'+'"]').utilNumberControl().val(data.JasaHrgBeli);
                            $('[id="'+rowid+'_'+'JasaGroup'+'"]').val(data.JasaGroup);
                            $('[id="'+rowid+'_'+'JasaKode'+'"]').val(data.JasaKode); // Select the option with a value of '1'
                            $('[id="'+rowid+'_'+'JasaKode'+'"]').trigger('change');
                            window.hitungLine();
						}
                    }              
                }
            },
            {
                name: 'JasaGroup',
                label: 'Group',
                editable: true,
                width: 120,
            },      
            {
                name: 'UJHrgBeliLama',
                label: 'Hrg Beli Lama',
                editable: true,
                width: 110,
                template: 'money',
                editoptions:{
                    readOnly:true,
                }, 
            },    
            {
                name: 'UJHrgBeliBaru',
                label: 'Hrg Beli Baru',
                editable: true,
                width: 110,
                template: 'money'
            },
            {
                name: 'UJHrgJualLama',
                label: 'Hrg Jual Lama',
                editable: true,
                width: 110,
                template: 'money',
                editoptions:{
                    readOnly:true,
                }, 
            },    
            {
                name: 'UJHrgJualBaru',
                label: 'Hrg Jual Baru',
                editable: true,
                width: 110,
                template: 'money'
            }, 
        ], 
     }).init().fit($('.box-body')).load({url: '$urlDetail'});
      
         $('#btnCancel').click(function (event) {	      
           $('#form_ttujhd_id').attr('action','{$url['cancel']}');
           $('#form_ttujhd_id').submit();
        });
	
        $('#btnSave').click(function (event) {	      
            $('input[name="SaveMode"]').val('ALL');
            $('#form_ttujhd_id').attr('action','{$url['update']}');
            $('#form_ttujhd_id').submit();
        }); 

       $('#btnPrint').click(function (event) {	      
        $('#form_ttujhd_id').attr('action','$urlPrint');
        $('#form_ttujhd_id').attr('target','_blank');
        $('#form_ttujhd_id').submit();
	  });   
JS
);

abengkel/views/ttujhd/create.php
<?php
use common\components\Custom;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Ttujhd */
$params                          = '&id=' . $id . '&action=create';
$cancel = Custom::url(\Yii::$app->controller->id.'/cancel'.$params );
$this->title                     = 'Tambah - Harga Jasa';
?>
<div class="ttujhd-create">
    <?= $this->render('_form', [
        'model'     => $model,
        'id'        =>$id,
        'dsSetup'   => $dsSetup,
        'url'       => [
            'update' => Custom::url( \Yii::$app->controller->id . '/update' . $params ),
            'print'  => Custom::url( \Yii::$app->controller->id . '/print' . $params ),
            'cancel' => $cancel,
            'detail' => Url::toRoute( [ 'ttujit/index','action' => 'create' ] ),
        ]
    ]) ?>

</div>

abengkel/views/ttujhd/index.php
<?php
use abengkel\assets\AppAsset;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Update Harga Jasa';
$this->params['breadcrumbs'][] = $this->title;
$arr                           = [
	'cmbTxt'    => [
		'UJNo'			=> 'No UJ',
		'UJKeterangan'  => 'Keterangan',
		'PosKode'       => 'Pos Kode',
		'KodeTrans'     => 'Kode Trans [TC]',
		'Cetak'         => 'Cetak',
		'UserID'        => 'User ID',
	],
	'cmbTgl'    => [
		'UJTgl'			=> 'Tanggal UJ',
	],
	'cmbNum'    => [
	],
	'sortname'  => "UJTgl",
	'sortorder' => 'desc'
];
$this->registerJsVar( 'setcmb', $arr );
AppAsset::register( $this );
?>
    <div class="panel panel-default">
        <div class="panel-body">
			<?= $this->render( '../_search' ); ?>
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
<?php
$this->registerJs( \abengkel\components\TdUi::mainGridJs( \abengkel\models\Ttujhd::className(), 'Update Harga Jasa',
    [
        'url_delete' => Url::toRoute( [ 'ttujhd/delete' ] ),
    ]), \yii\web\View::POS_READY );

abengkel/views/ttujhd/update.php
<?php
use common\components\Custom;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Ttujhd */
$params                          = '&id=' . $id . '&action=update';
$cancel = Custom::url(\Yii::$app->controller->id.'/cancel'.$params );
$this->title                     = 'Edit - Harga Jasa: ' . $model->UJNo;
?>
<div class="ttujhd-update">
    <?= $this->render('_form', [
        'model'     => $model,
        'id'        =>$id,
        'dsSetup'   => $dsSetup,
        'url'       => [
            'update' => Custom::url( \Yii::$app->controller->id . '/update' . $params ),
            'print'  => Custom::url( \Yii::$app->controller->id . '/print' . $params ),
            'cancel' => $cancel,
            'detail' => Url::toRoute( [ 'ttujit/index','action' => 'update' ] ),
        ]
    ]) ?>

</div>