abengkel/models/Tdcustomer.php
<?php

namespace abengkel\models;

/**
 * This is the model class for table "tdcustomer".
 *
 * @property string $MotorNoPolisi
 * @property string $MotorNoMesin
 * @property string $MotorNoRangka
 * @property string $CusKTP
 * @property string $CusNama
 * @property string $CusAlamat
 * @property string $CusRT
 * @property string $CusRW
 * @property string $CusProvinsi
 * @property string $CusKabupaten
 * @property string $CusKecamatan
 * @property string $CusKelurahan
 * @property string $CusKodePos
 * @property string $CusTelepon
 * @property string $CusSex
 * @property string $CusTempatLhr
 * @property string $CusTglLhr
 * @property string $CusAgama
 * @property string $CusPekerjaan
 * @property string $CusEmail
 * @property string $CusKeterangan
 * @property string $CusKK
 * @property string $CusStatus
 * @property string $MotorType
 * @property string $MotorWarna
 * @property string $MotorTahun
 * @property string $MotorNama
 * @property string $MotorKategori
 * @property string $MotorCC
 * @property string $TglAkhirServis
 * @property string $AHASSNomor
 * @property string $TglBeli
 * @property string $NoBukuServis
 * @property string $CusJenis
 */
class Tdcustomer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tdcustomer';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['MotorNoPolisi'], 'required'],
            [['CusTglLhr', 'TglAkhirServis', 'TglBeli'], 'safe'],
            [['MotorTahun', 'MotorCC'], 'number'],
            [['MotorNoPolisi', 'CusSex'], 'string', 'max' => 12],
            [['MotorNoMesin', 'MotorNoRangka'], 'string', 'max' => 25],
            [['CusKTP'], 'string', 'max' => 18],
            [['CusNama', 'CusKabupaten', 'CusKecamatan', 'CusKelurahan', 'CusEmail', 'MotorType'], 'string', 'max' => 50],
            [['CusAlamat'], 'string', 'max' => 75],
            [['CusRT', 'CusRW'], 'string', 'max' => 3],
            [['CusProvinsi', 'CusTelepon', 'CusTempatLhr'], 'string', 'max' => 30],
            [['CusKodePos'], 'string', 'max' => 7],
            [['CusAgama', 'MotorKategori'], 'string', 'max' => 15],
            [['CusPekerjaan', 'MotorWarna'], 'string', 'max' => 35],
            [['CusKeterangan','CusJenis', 'MotorNama'], 'string', 'max' => 100],
            [['CusKK'], 'string', 'max' => 16],
            [['CusStatus'], 'string', 'max' => 1],
            [['AHASSNomor'], 'string', 'max' => 10],
            [['NoBukuServis'], 'string', 'max' => 20],
            [['MotorNoPolisi'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'MotorNoPolisi' => 'Motor No Polisi',
            'MotorNoMesin' => 'Motor No Mesin',
            'MotorNoRangka' => 'Motor No Rangka',
            'CusKTP' => 'Cus Ktp',
            'CusNama' => 'Cus Nama',
            'CusAlamat' => 'Cus Alamat',
            'CusRT' => 'Cus Rt',
            'CusRW' => 'Cus Rw',
            'CusProvinsi' => 'Cus Provinsi',
            'CusKabupaten' => 'Cus Kabupaten',
            'CusKecamatan' => 'Cus Kecamatan',
            'CusKelurahan' => 'Cus Kelurahan',
            'CusKodePos' => 'Cus Kode Pos',
            'CusTelepon' => 'Cus Telepon',
            'CusSex' => 'Cus Sex',
            'CusTempatLhr' => 'Cus Tempat Lhr',
            'CusTglLhr' => 'Cus Tgl Lhr',
            'CusAgama' => 'Cus Agama',
            'CusPekerjaan' => 'Cus Pekerjaan',
            'CusEmail' => 'Cus Email',
            'CusKeterangan' => 'Cus Keterangan',
            'CusKK' => 'Cus Kk',
            'CusStatus' => 'Cus Status',
            'MotorType' => 'Motor Type',
            'MotorWarna' => 'Motor Warna',
            'MotorTahun' => 'Motor Tahun',
            'MotorNama' => 'Motor Nama',
            'MotorKategori' => 'Motor Kategori',
            'MotorCC' => 'Motor Cc',
            'TglAkhirServis' => 'Tgl Akhir Servis',
            'AHASSNomor' => 'Ahass Nomor',
            'TglBeli' => 'Tgl Beli',
            'NoBukuServis' => 'No Buku Servis',
            'CusJenis' => 'Jenis',
        ];
    }


	public static function colGrid()
	{
		return [
			'MotorNoPolisi'     => ['width' => 80,'label' => 'No Polisi ','name'  => 'MotorNoPolisi'],
			'MotorNoMesin'      => ['width' => 90,'label' => 'No Mesin','name'  => 'MotorNoMesin'],
			'MotorNama'			=> ['width' => 200,'label' => 'Motor','name'  => 'MotorNama'],
			'MotorWarna'			=> ['width' => 200,'label' => 'Motor Warna','name'  => 'MotorWarna'],
			'CusNama'           => ['width' => 150,'label' => 'Nama','name'  => 'CusNama'],
			'CusKabupaten'      => ['width' => 100,'label' => 'Kabupaten','name'  => 'CusKabupaten'],
			'CusKecamatan'      => ['width' => 100,'label' => 'Kecamatan','name'  => 'CusKecamatan'],
			'CusTelepon'         => ['width' => 100,'label' => 'Telepon','name'  => 'CusTelepon'],
			'MotorNoRangka'         => ['width' => 100,'label' => 'No Rangka','name'  => 'MotorNoRangka'],
			'MotorType'         => ['width' => 100,'label' => 'Motor Type','name'  => 'MotorType'],
			'MotorKategori'         => ['width' => 100,'label' => 'Motor Kategory','name'  => 'MotorKategori'],
    /*
			'AHASSNomor'         => ['width' => 100,'label' => 'AHASSNomor','name'  => 'AHASSNomor'],
    */
		];
	}

	public function getData($param = null){
		return $this->toArray();
	}

	public function getAhass() {
		return $this->hasOne( Tdahass::className(), [ 'AHASSNomor' => 'AHASSNomor' ] );
	}
    /**
     * {@inheritdoc}
     * @return TdcustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TdcustomerQuery(get_called_class());
    }
}

abengkel/controllers/TdcustomerController.php
<?php

namespace abengkel\controllers;

use abengkel\components\AbengkelController;
use abengkel\components\Menu;
use abengkel\components\TdAction;
use abengkel\components\TUi;
use abengkel\models\Tdcustomer;
use common\components\General;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * TdcustomerController implements the CRUD actions for Tdcustomer model.
 */
class TdcustomerController extends AbengkelController
{

    public function beforeAction($action)
    {
        $GLOBALS['MenuText'] = 'Konsumen';
        switch ($action->id) {
            case 'create':
                $this->isAllow = Menu::akses($GLOBALS['MenuText'], Menu::ADD);
                break;
            case 'update':
                $this->isAllow = Menu::akses($GLOBALS['MenuText'], Menu::UPDATE);
                break;
            case 'delete':
                $this->isAllow = Menu::akses($GLOBALS['MenuText'], Menu::DELETE);
                break;
            case 'index':
                $this->isAllow = Menu::akses($GLOBALS['MenuText'], Menu::DISPLAY);
                break;
            case 'td':
            case 'cancel':
                $this->isAllow = 1;
                break;
        }
//		if($this->isAllow == 0) throw new ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        return true;
    }

    public function actions()
    {
        return [
            'td' => [
                'class' => TdAction::class,
                'model' => Tdcustomer::class,
                'joinWith' => [
                    'ahass' => [
                        'type' => 'INNER JOIN'
                    ]
                ]
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tdcustomer models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionSelect()
    {
        $this->layout = 'select-mode';
        return $this->render('index', [
            'mode' => self::MODE_SELECT
        ]);
    }

    /**
     * Finds the Tdcustomer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param string $id
     *
     * @return Tdcustomer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tdcustomer::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Tdcustomer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        TUi::$actionMode = Menu::ADD;
        $model = new Tdcustomer();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['tdcustomer/update', 'id' => $this->generateIdBase64FromModel($model), 'action' => 'display']);
        } else {
            Yii::$app->session->addFlash('warning', Html::errorSummary($model));
        }
        return $this->render('create', [
            'model' => $model,
            'id' => 'new'
        ]);
    }

    /**
     * Updates an existing Tdcustomer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param string $id
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $action = $_GET['action'];
        switch ($action) {
            case 'create':
            case 'update':
                TUi::$actionMode = Menu::UPDATE;
                break;
            case 'view':
                TUi::$actionMode = Menu::VIEW;
                break;
            case 'display':
                TUi::$actionMode = Menu::DISPLAY;
                break;
        }
        $model = $this->findModelBase64('Tdcustomer', $id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['tdcustomer/update', 'id' => $this->generateIdBase64FromModel($model), 'action' => 'display']);
        } else {
            Yii::$app->session->addFlash('warning', Html::errorSummary($model));
        }
        return $this->render('update', [
            'model' => $model,
            'id' => $this->generateIdBase64FromModel($model),
        ]);
    }
    /**
     * Deletes an existing Tdcustomer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param string $id
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
//	public function actionDelete( $id ) {
//		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
//		$model                       = $model = $this->findModelBase64( 'Tdcustomer', $id );
//		if ( $model != null ) {
//			$result[ 'status' ] = $model->delete();
//		}
//		if ( $result[ 'status' ] !== false ) {
//			return $this->responseSuccess( 'Konsumen berhasil dihapus' );
//		} else {
//			return $this->responseFailed( 'Konsumen gagal dihapus' );
//		}
//	}

    public function actionDelete()
    {
        /** @var Tdcustomer $model */
        $request = Yii::$app->request;
        if ($request->isAjax) {
            $model = $this->findModelBase64('Tdcustomer', $_POST['id']);
            if ($model != null) {
                $result['status'] = $model->delete();
            }
            if ($result['status'] !== false) {
                $model = Tdcustomer::find()->one();
                return $this->redirect(['tdcustomer/update', 'id' => $this->generateIdBase64FromModel($model), 'action' => 'display']);
            } else {
                return $this->responseFailed('Konsumen gagal dihapus');
            }
        }
    }


    public function actionFindCombo()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return Tdcustomer::find()->combo($_POST);
    }

    public function actionFindById($id)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return Tdcustomer::find()
            ->where('MotorNoPolisi = :MotorNoPolisi', [':MotorNoPolisi' => $id])
            ->asArray()->one();
    }

    public function actionCancel($id, $action)
    {
        $model = Tdcustomer::findOne($id);
        if ($model == null) {
            $model = Tdcustomer::find()->one();
            if ($model == null) {
                return $this->redirect(['tdcustomer/index']);
            }
        }
        return $this->redirect(['tdcustomer/update', 'id' => $this->generateIdBase64FromModel($model), 'action' => 'display']);
    }

    public function actionEdit($id)
    {
        $model = $this->findModelBase64('Tdcustomer', $id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($this->isPopupForm()) {
                $data = Tdcustomer::find()
                    ->where('MotorNoPolisi = :MotorNoPolisi', [':MotorNoPolisi' => $model->MotorNoPolisi])
                    ->asArray()->one();
                return $this->responseToPopupForm($data);
            } else {
                return $this->redirect(['tdcustomer/update', 'id' => $this->generateIdBase64FromModel, 'action' => 'display']);
            }
        }
        if ($this->isPopupForm()) {
            $this->setLayoutForPopupForm();
        }
        return $this->render('edit', [
            'model' => $model,
            'id' => $this->generateIdBase64FromModel($model),
        ]);
    }

    public function actionLoadCustomer()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $query = General::cCmd("Select tdcustomer.*, tdahass.AHASSNama  FROM tdcustomer 
    	LEFT JOIN tdahass ON tdahass.AHASSNomor = tdcustomer.AHASSNomor WHERE MotorNoPolisi = :MotorNoPolisi", [
            ':MotorNoPolisi' => $_POST['Tdcustomer']['MotorNoPolisi']
        ])->queryOne();
        return $query;
    }

    public function actionSaveCustomer()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = Tdcustomer::findOne($_POST['Tdcustomer']['MotorNoPolisi']);
        $msg = 'Berhasil update konsumen';
        if ($_POST['oper'] == 'Add' && $model == null) {
            $model = new Tdcustomer;
            $msg = 'Berhasil tambah konsumen';
        }
        $model->load($_POST);
        if (!$model->save()) {
            return [
                'status' => false,
                'msg' => Html::errorSummary($model)
            ];
        }
        return [
            'status' => true,
            'msg' => $msg
        ];
    }
}

abengkel/views/tdcustomer/create.php
<?php
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Tdcustomer */

$this->title = 'Tambah Konsumen';
$this->params['breadcrumbs'][] = ['label' => 'Konsumen', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tdcustomer-create">
    <?= $this->render('_form', [
        'model' => $model,
        'id'    => $id,
        'url'   => [
            'update'   => Url::toRoute( [ 'tdcustomer/create','action' => 'create' ] ),
            'cancel' => Url::toRoute( [ 'tdcustomer/cancel', 'id' => $id,'action' => 'create' ] )
        ]
    ]) ?>

</div>

abengkel/views/tdcustomer/edit.php
<?php
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Tdcustomer */

$this->title = 'Edit Konsumen : ' . $model->MotorNoPolisi;
$this->params['breadcrumbs'][] = ['label' => 'Konsumen', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="tdcustomer-update">
    <?= $this->render('_formedit', [
        'model' => $model,
        'id'    => $id,
        'url'   => [
            'update'   => Url::toRoute( [ 'tdcustomer/update', 'id' => $id ] ),
            'cancel' => Url::toRoute( [ 'tdcustomer/cancel', 'id' => $id,'action' => 'update' ] )
        ]
    ]) ?>

</div>

abengkel/views/tdcustomer/index.php
<?php
use abengkel\assets\AppAsset;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Konsumen';
$this->params['breadcrumbs'][] = $this->title;
$arr                           = [
	'cmbTxt' => [
		'MotorNoPolisi'  => 'No Polisi',
		'MotorNoMesin'   => 'No Mesin',
		'MotorNoRangka'  => 'No Rangka',
		'CusKTP'         => 'Cus Ktp',
		'CusNama'        => 'Cus Nama',
		'CusAlamat'      => 'Cus Alamat',
		'CusRT'          => 'Cus Rt',
		'CusRW'          => 'Cus Rw',
		'CusProvinsi'    => 'Cus Provinsi',
		'CusKabupaten'   => 'Cus Kabupaten',
		'CusKecamatan'   => 'Cus Kecamatan',
		'CusKelurahan'   => 'Cus Kelurahan',
		'CusKodePos'     => 'Cus Kode Pos',
		'CusTelepon'     => 'Cus Telepon',
		'CusSex'         => 'Cus Sex',
		'CusTempatLhr'   => 'Cus Tempat Lhr',
		'CusAgama'       => 'Cus Agama',
		'CusPekerjaan'   => 'Cus Pekerjaan',
		'CusEmail'       => 'Cus Email',
		'CusKeterangan'  => 'Cus Keterangan',
		'CusKK'          => 'Cus Kk',
		'CusStatus'      => 'Cus Status',
		'MotorType'      => 'Motor Type',
		'MotorWarna'     => 'Motor Warna',
		'MotorTahun'     => 'Motor Tahun',
		'MotorNama'      => 'Motor Nama',
		'MotorKategori'  => 'Motor Kategori',
		'MotorCC'        => 'Motor Cc',
		'AHASSNomor'     => 'Ahass Nomor',
		'NoBukuServis'   => 'No Buku Servis',
	],
	'cmbTgl' => [
		'TglAkhirServis' => 'Tgl Akhir Servis',
		'TglBeli'        => 'Tgl Beli',
		'CusTglLhr'      => 'Cus Tgl Lhr',
	],
	'cmbNum' => [
	],
	'sortname'  => "CusStatus, MotorNoPolisi ",
	'sortorder' => ''
];
$this->registerJsVar( 'setcmb', $arr );
AppAsset::register( $this );
?>
    <div class="panel panel-default">
        <div class="panel-body">
			<?= $this->render( '../_search' ); ?>
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
<?php
$this->registerJs( \abengkel\components\TdUi::mainGridJs( \abengkel\models\Tdcustomer::className(),
    'Konsumen',[
            'mode'=> isset($mode)? $mode : ''
    ] ), \yii\web\View::POS_READY );

abengkel/views/tdcustomer/update.php
<?php
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model abengkel\models\Tdcustomer */

$this->title = 'Edit Konsumen : ' . $model->MotorNoPolisi;
$this->params['breadcrumbs'][] = ['label' => 'Konsumen', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="tdcustomer-update">
    <?= $this->render('_form', [
        'model' => $model,
        'id'    => $id,
        'url'   => [
            'update'   => Url::toRoute( [ 'tdcustomer/update', 'id' => $id ,'action' => 'update'] ),
            'cancel' => Url::toRoute( [ 'tdcustomer/cancel', 'id' => $id,'action' => 'update' ] )
        ]
    ]) ?>

</div>